Fixes #302.
JelteF/PyLaTeX pull request #305
Opened 2020-09-24 02:48 UTC by zthurman

@JelteF Testall.sh passed on my Windows 10 and Manjaro both. Let me know how it looks on your side

2020-10-03 11:56 UTC, JelteF requested changes
Thanks for the contribution! Left some small comments.

2020-10-03 11:56 UTC, JelteF commented on pylatex/utils.py
> +            filename = '.'.join(file_parts[0:-1]) + '.' + file_parts[-1]
This seems like a very convoluted way to make the filename end up in the same way that it already was. I think it makes more sense to change this:
```python
len(file_parts) > 2
```
To:
```python
os.name == 'posix' and len(file_parts) > 2
```

And keep the rest at it originally was (no extra `else` block)

2020-10-03 11:56 UTC, JelteF commented on pylatex/utils.py
> +    Windows gets angry about the brackets that resolve the above issue on linux
```suggestion
    Windows gets angry about the curly braces that resolve the above issue on linux
```

2020-10-03 11:56 UTC, JelteF commented on tests/test_utils_fix_filename.py
> +    if os.name == 'posix':
Is it possible to test both, by manually changing `os.name`?
Something like this:
```python
original_os_name = os.name
try:
    os.name = 'posix'
    assert fix_filename(fname) == "{aa.a}.a"
    os.name = 'nt'
    assert fix_filename(fname) == "aa.a.a"
finally:
    os.name = original_os_name
```

2020-10-03 16:56 UTC, zthurman reviewed
Added requested changes, example and tests still working on both linux and Windows.

2020-10-18 09:09 UTC, JelteF commented
This is merged and released as 1.4.1

2020-10-18 09:11 UTC, closed without merging